In [6]:
import numpy as np
vector=np.array([1,2,3,4,5])
print(vector)
print(type(vector))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#2D And 3d
matrix=np.array([[1,2,3,4],[5,6,7,8]])
print(matrix)

# now 3d 
three_d=np.array([[[1,2],[3,4],[5,6]]])
print(three_d) # this called tensor 


[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]
  [5 6]]]


In [ ]:
#dtype

a=np.array([1,2,3,4],dtype=float)
b=np.array([1,2,3,4],dtype=str)

print(a)
print(b)

[1. 2. 3. 4.]
['1' '2' '3' '4']


In [ ]:
# np arange()
np.arange(1,11) # similar as the range fun in python

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# with reshape
np.arange(1,11).reshape(2,5) # 2=rows 5=columns

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [26]:
# np.ones & np.zeros
ones=np.ones((3,4),dtype=int)
zero=np.zeros((3,4))
print(ones)
print()
print(zero)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
# np.random
np.random.random((3,4))

array([[0.57818811, 0.80612905, 0.81664427, 0.88599863],
       [0.78204345, 0.88901452, 0.04549046, 0.40062579],
       [0.84361543, 0.3584685 , 0.76791892, 0.49880795]])

In [ ]:
# np.linspace
np.linspace(-10,10,10)
# -10=lower limit, 10= upper limit and 10 is the how many numbers want to generate


array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
np.linspace(-10,10,4)
# give the linery separate points

array([-10.        ,  -3.33333333,   3.33333333,  10.        ])

In [ ]:
# np.identity
np.identity(3) # gives the identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Attributes

In [ ]:
import numpy as np
a1=np.arange(10)
a2=np.arange(12).reshape(4,3)
a3=np.arange(8).reshape(2,2,2)

print(f"a1:\n{a1}")
print()
print(f"a2:\n{a2}")
print()
print(f"a3:\n{a3}")
print()

a1:
[0 1 2 3 4 5 6 7 8 9]

a2:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

a3:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]



In [ ]:
# ndim
print(a1.ndim) # of dimentions
print(a2.ndim)
print(a3.ndim)

1
2
3


In [ ]:
#shape
print(a1.shape) #tells about te shape of the array
print(a2.shape)
print(a3.shape)

(10,)
(4, 3)
(2, 2, 2)


In [ ]:
# size
print(a1.size) # tells about the size of the array
print(a2.size)
print(a3.size)

10
12
8


In [ ]:
# itemsize
print(a1.itemsize) # tells that how much memory size is talking every item
print(a2.itemsize) # all are int 
print(a3.itemsize)

8
8
8


In [19]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
int64
int64


### Changing Datatype

In [24]:
# astype
a1.astype(np.int32)
print(a1.dtype)
print(a2.astype(float))

int64
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


## Array Operations

In [ ]:
# Scalar OPerations

arry=np.arange(12)
print(arry) # original one
new_one=arry * 2
print(new_one) # updated 

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  2  4  6  8 10 12 14 16 18 20 22]


In [33]:
var=arry **2 # takes the square of the entire array
print(var)

[  0   1   4   9  16  25  36  49  64  81 100 121]


In [35]:
# relational Operators
print(var > 5)

[False False False  True  True  True  True  True  True  True  True  True]


In [ ]:
# vectors opereations

arr1=np.arange(12,24).reshape(3,4)

arr2=np.arange(1,13).reshape(3,4)
arr1 / arr2 # divide it 

array([[12.        ,  6.5       ,  4.66666667,  3.75      ],
       [ 3.2       ,  2.83333333,  2.57142857,  2.375     ],
       [ 2.22222222,  2.1       ,  2.        ,  1.91666667]])

In [ ]:
arr1 * arr2  # multiply two array

array([[ 12,  26,  42,  60],
       [ 80, 102, 126, 152],
       [180, 210, 242, 276]])

#### Array Functions

In [3]:
A1=np.random.random((4,4)) # 4 rows and 4 columns
round=np.round(A1 * 100)
print(round)

[[ 65.  92.  51.   9.]
 [ 96.  39.  41.  89.]
 [ 10.  68.  23.  56.]
 [100.  44.  43.  83.]]


In [4]:
# max/min/sum/prod
max=np.max(round)
min=np.min(round)
print(max)
print(min)
print(np.sum(round)) # gives the sum of the all items
print(np.prod(round)) # gives the product of the all elements

100.0
9.0
909.0
5.157599001543696e+26


In [5]:
#  for axis row=1 and col=0 
print(f"Original Matrix:\n {round}\n")

column_wise_max=np.max(round, axis=0)
row_wise_max=np.max(round, axis=1)
print(f"Column wise max:\n{column_wise_max}\n")
print(f"Row wise max:\n {row_wise_max}")

Original Matrix:
 [[ 65.  92.  51.   9.]
 [ 96.  39.  41.  89.]
 [ 10.  68.  23.  56.]
 [100.  44.  43.  83.]]

Column wise max:
[100.  92.  51.  89.]

Row wise max:
 [ 92.  96.  68. 100.]


#### Mean/Median/Std/Var

In [6]:
import numpy as np
mean=np.mean(round,axis=1) # row wise mean
median=np.median(round,axis=1)
standard_deviation=np.std(round,axis=0) # column wise std
varience=np.var(round,axis=0) # column wise varience is taken 
print(mean)
print(median)
print(standard_deviation)
print(varience)

[54.25 66.25 39.25 67.5 ]
[58.  65.  39.5 63.5]
[35.98871351 21.11131213 10.23474475 31.56243812]
[1295.1875  445.6875  104.75    996.1875]


In [ ]:
# trignomatrix fumction
np.sin(round) # similar can be done others

array([[ 0.82682868, -0.77946607,  0.67022918,  0.41211849],
       [ 0.98358775,  0.96379539, -0.15862267,  0.86006941],
       [-0.54402111, -0.89792768, -0.8462204 , -0.521551  ],
       [-0.50636564,  0.01770193, -0.83177474,  0.96836446]])

In [ ]:
# dot product of two matrix
mat1=np.arange(1,11).reshape(5,2)
mat2=np.arange(20,30).reshape(2,5)
# now dot product 
product=np.dot(mat1,mat2)
product

array([[ 70,  73,  76,  79,  82],
       [160, 167, 174, 181, 188],
       [250, 261, 272, 283, 294],
       [340, 355, 370, 385, 400],
       [430, 449, 468, 487, 506]])

In [12]:
# log and exponents
log=np.log(mat1)
exp=np.exp(mat1)
print(f"{log}\n")
print(exp)

[[0.         0.69314718]
 [1.09861229 1.38629436]
 [1.60943791 1.79175947]
 [1.94591015 2.07944154]
 [2.19722458 2.30258509]]

[[2.71828183e+00 7.38905610e+00]
 [2.00855369e+01 5.45981500e+01]
 [1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03]
 [8.10308393e+03 2.20264658e+04]]


In [ ]:
# round, floor and ceil

round=np.round(np.random.random((2,3))*100)
floor=np.floor(np.random.random((2,3))*100)
ceil=np.ceil(np.random.random((2,3))*100)

print(f"Round:\n {round}\n")
print(f"Floor:\n {floor}\n")
print(f"Ceil:\n {ceil}\n")

Round:
 [[18.  4. 67.]
 [31. 98. 42.]]

Floor:
 [[ 3. 85.  4.]
 [97. 28. 69.]]

Ceil:
 [[97. 67. 85.]
 [ 7. 16. 15.]]



## Indexcing and Slicing

In [23]:
one_d=np.arange(10)
two_d=np.arange(12).reshape(3,4)
three_d=np.arange(27).reshape(3,3,3)

print(f"one dimentional:\n{one_d}\n")
print(f"Two dimentional:\n{two_d}\n")
print(f"Two dimentional:\n{three_d}")

one dimentional:
[0 1 2 3 4 5 6 7 8 9]

Two dimentional:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Two dimentional:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
